### ISSUE TITLE
Potentially invalid values in Heartbeat handling

### ISSUE THREAD

**Issue by vinzenz** [ayufan/niimprint-web#1]
https://github.com/ayufan/niimprint-web/blob/89981755477bcfce06f7a4acb12bdeed480a9241/cmds.js#L117-L119

Index -2  appears twice here, once for rfidreadstate and once for closingstate

That seems to be a mistake.

**Comment by ayufan** [comment]
@vinzenz No this is deliberate, it is "taken as-is" from the: https://github.com/kjy00302/niimprint/blob/main/niimprint/printerclient.py#L141.

**Comment by vinzenz** [comment]
@ayufan  Thanks for the clarification :-) 👍
